DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='nodeuser') THEN
        CREATE ROLE nodeuser CREATEDB CREATEROLE LOGIN PASSWORD 'U53r@N0d3';
    END IF;
END
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    CREATE SCHEMA IF NOT EXISTS node;

    GRANT USAGE ON SCHEMA node TO nodeuser;

    DROP TYPE IF EXISTS node.user_type;

    CREATE TYPE node.user_type AS ENUM (
        'ADMIN',
        'USER'
    );

    CREATE TABLE IF NOT EXISTS node.user (
        id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        name CHARACTER VARYING(50)  NOT NULL,
        username CHARACTER VARYING(20) NOT NULL,
        email CHARACTER VARYING(50) NOT NULL,
        password CHARACTER VARYING(75) NOT NULL,
        created_datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        updated_datetime TIMESTAMP WITHOUT TIME ZONE,
        is_deleted BOOLEAN DEFAULT false,
        CONSTRAINT user_pkey PRIMARY KEY (id),
        CONSTRAINT user_ukey UNIQUE (username)
    );

    INSERT INTO node.user(
                            name,
                            username,
                            email,
                            password,
                            created_datetime,
                            updated_datetime
                        )
    VALUES (
        'Super Admin', 
        'superadmin', 
        'superadmin@node.com', 
        '$2b$05$FWr5GaR6j1RwO435dtmau.aJVQrk/G4LFp5z8eYgG07chIQ5xq1TG', 
        CURRENT_TIMESTAMP, 
        CURRENT_TIMESTAMP
    );
END
$$ LANGUAGE plpgsql;