name: CI/CD Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm i

    - name: Run tests
      run: npm test

    - name: Run Security Scans
      run: npm audit

    - name: Handle Scan Results
      run: |
        if [ -z "$(npm audit --json)" ]; then
          echo "No vulnerabilities found. Continuing..."
        else
          echo "Vulnerabilities found. Failing the workflow."
          exit 1
        fi

    if: ${{ success() }}
